<?php

/*****
*
* @Author: Nasid Kamal.
* @Project Keyword: OHS.
*
*****/

defined('BASEPATH') OR exit('No direct script access allowed');

?>
<div class="row">
    <div class="col-md-12">
      	<div class="box box-info">
            <div class="box-header with-border">
              	<h3 style="color: #ffffff;" class="box-title">ADD NEW USER</h3>
            </div>
            <?php echo form_open('user/add'); ?>
          	<div class="box-body">
          		<div class="row clearfix">
          			<div class="col-sm-12">
						<div class="col-sm-2">
							<label for="pictureFile">User's Picture</label>
						</div>
						<div class="col-sm-3">
							<!-- <img src="<?php //echo site_url('resources/img/user_default.png');?>" style="height: 120px; width: 100px;" alt="Worker Image"> -->
							<img src="<?php echo site_url('resources/img/user_default.png');?>" style="height: 120px; width: 100px;" alt="Worker Image">
							<div style="min-height: 10px;"></div>
							<div id="results" ></div>
							<input type="hidden" id="pictureDataURI" name="pictureDataURI" value="">

						</div>
						<div class="col-sm-4">
							
							
							<div id="ohs_webcam" style="height: 240px; width: 200px; align-content: center; border: 0.5px solid skyblue;">
								<div style="padding-top: 90px; text-align: center;">
									<a name="capture_picture" id="capture_picture" class="btn btn-info" href="">
										<i class="fa fa-camera-retro"></i> CAPTURE PICTURE
									</a>
								</div>
							</div>

							<br>

							<div style=" padding-left: 40px; text-align: center;"><input type="button" id="take_snapshot" value="Take Snapshot"></div>

							
							
							<!-- <button name="take_snapshot" id="take_snapshot" class="btn btn-info btn-lg">
								<i class="fa fa-camera-retro"></i> TAKE SNAPSHOT
							</button> -->

							<br>
							<br>
						</div>
						<div style="padding-top: 100px;" class="col-sm-3">
							
							UPLOAD PICTURE<input type="file" id="pictureFile" name="pictureFile">


						</div>
					</div>
					<div class="col-sm-12">
						<h4 class="page-info">BASIC INFORMATION</h4>
						<div class="col-md-4">
							<label for="roleId" class="control-label">User Type</label>
							<div class="form-group">
								<select id="ohs-utid" name="roleId" class="form-control">
									<?php 
									if($user_session['roleId'] != 2) {

										foreach($all_roles as $role)
										{
											$selected = ($role['id'] == $this->input->post('roleId')) ? ' selected="selected"' : "";

											echo '<option value="'.$role['id'].'" '.$selected.'>'.$role['title'].'</option>';
										}

									} else {

										echo '<option value="3" selected="selected">CONSTRUCTION_COMPANY_USER</option>';

									}
									?>
								</select>
							</div>
						</div>
						<?php
						
							$currentTime = time();
							$hexTime = dechex($currentTime);

							$cryptoStrong = true; // can be false
							$length = 8; // Any length you want
							$bytes = openssl_random_pseudo_bytes($length, $cryptoStrong);
							$randomString = bin2hex($bytes);

						?>
						<input type="hidden" name="generatedUID" value="<?php echo $randomString; ?>"  />
						<div class="col-md-4">
							<label for="uid" class="control-label">UID (Autogenerated)</label>
							<div class="form-group">
								<input type="text" name="uid" value="<?php echo $randomString; ?>" class="form-control" id="uid" disabled="disabled" />
							</div>
						</div>
						<div class="col-md-4">
							<label for="fullName" class="control-label">Full Name</label>
							<div class="form-group">
								<input type="text" name="fullName" value="<?php echo $this->input->post('fullName'); ?>" class="form-control" id="fullName" />
							</div>
						</div>
						<div class="col-md-4">
							<label for="statusId" class="control-label">User Status</label>
							<div class="form-group">
								<select name="statusId" class="form-control">
									<?php 
									foreach($all_user_statuses as $user_status)
									{
										$selected = ($user_status['id'] == $this->input->post('statusId')) ? ' selected="selected"' : "";

										echo '<option value="'.$user_status['id'].'" '.$selected.'>'.$user_status['title'].'</option>';
									} 
									?>
								</select>
							</div>
						</div>
						<div class="col-md-4">
							<label for="username" class="control-label">Username</label>
							<div class="form-group">
								<input type="text" name="username" value="<?php echo $this->input->post('username'); ?>" class="form-control" id="username" />
							</div>
						</div>
						<div class="col-md-4">
							<label for="password" class="control-label">Password</label>
							<div class="form-group">
								<input type="password" name="password" value="<?php echo $this->input->post('password'); ?>" class="form-control" id="password" />
							</div>
						</div>
						<div class="col-md-4">
							<label for="email" class="control-label">Email</label>
							<div class="form-group">
								<input type="text" name="email" value="<?php echo $this->input->post('email'); ?>" class="form-control" id="email" />
							</div>
						</div>
						<div class="col-md-4">
							<label for="address1" class="control-label">Address #1</label>
							<div class="form-group">
								<input type="text" name="address1" value="<?php echo $this->input->post('address1'); ?>" class="form-control" id="address1" />
							</div>
						</div>
						<div class="col-md-4">
							<label for="address2" class="control-label">Address #2</label>
							<div class="form-group">
								<input type="text" name="address2" value="<?php echo $this->input->post('address2'); ?>" class="form-control" id="address2" />
							</div>
						</div>
						<div class="col-md-4">
							<label for="city" class="control-label">City</label>
							<div class="form-group">
								<input type="text" name="city" value="<?php echo $this->input->post('city'); ?>" class="form-control" id="city" />
							</div>
						</div>
						<div class="col-md-4">
							<label for="state" class="control-label">State</label>
							<div class="form-group">
								<input type="text" name="state" value="<?php echo $this->input->post('state'); ?>" class="form-control" id="state" />
							</div>
						</div>
						<div class="col-md-4">
							<label for="zipCode" class="control-label">Zip Code</label>
							<div class="form-group">
								<input type="text" name="zipCode" value="<?php echo $this->input->post('zipCode'); ?>" class="form-control" id="zipCode" />
							</div>
						</div>
						<div id="foreperson-user-role">
							<div class="col-md-2">
								<label for="Foreman" class="control-label">Foreperson</label>
							</div>
							<div class="col-md-4">
								<input type="checkbox" id="Foreman" name="Foreman" value="1" <?php if($this->input->post('Foreman') == '1') { echo ' checked="checked"'; } ?> /><span></span>&nbsp;&nbsp;<i>Check to provide <b>"Foreperson"</b> role.</i>
							</div>
						</div>
						<div id="drug-test-collector">
							<div class="col-md-2">
								<label for="drugTestCollector" class="control-label">Drug Test Collector</label>
							</div>
							<div class="col-md-4">
								<input type="checkbox" id="drugTestCollector" name="drugTestCollector" value="1" <?php if($this->input->post('drugTestCollector') == '1') { echo ' checked="checked"'; } ?> /><span></span>&nbsp;&nbsp;<i>Check to provide <b>"Drug Test Collector"</b> role.</i>
							</div>
						</div>
					</div>
          			<div class="col-sm-12" style="min-height: 400px;">
						<h4 class="page-info">USER AUTHORITY</h4>
						<div class="col-md-2">
							<h5>COMPANIES</h5>
							<input type="hidden" name="cid_str" id="cid_str" value="">
							<input type="hidden" name="c-selected-count" id="c-selected-count" value="0">
							<div id="selectedCList" style="height: 300px; overflow: auto; border: 0.5px solid gray; border-radius: 15px;">
                            </div>
                        </div>
						<div class="col-md-2">
							<input type="hidden" name="c_search_api_url" id="c_search_api_url" value="<?= site_url('company/search?key='); ?>">
                            <input style="border-radius: 15px;" type="text" class="form-control" name="company-key" id="company-key" placeholder="SEARCH COMPANIES">
							<div id="fullCList" style="height: 300px; overflow: auto; border: 0.5px solid gray; border-radius: 15px;">
							</div>
						</div>
						<div class="col-md-2">
							<h5>SUBCONTRACTORS</h5>
							<input type="hidden" name="scid_str" id="scid_str" value="">
							<input type="hidden" name="sc-selected-count" id="sc-selected-count" value="0">
							<div id="selectedScList" style="height: 300px; overflow: auto; border: 0.5px solid gray; border-radius: 15px;">
                            </div>
                        </div>
						<div class="col-md-2">
							<input type="hidden" name="sc_search_api_url" id="sc_search_api_url" value="<?= site_url('company/scsearch?key='); ?>">
                            <input style="border-radius: 15px;" type="text" class="form-control" name="subcontractor-key" id="subcontractor-key" placeholder="SEARCH SUBCONTRACTORS">
							<div id="fullScList" style="height: 300px; overflow: auto; border: 0.5px solid gray; border-radius: 15px;">
							</div>
						</div>
						<div class="col-md-2">
							<h5>SITES</h5>
							<input type="hidden" name="sid_str" id="sid_str" value="">
							<input type="hidden" name="selected-count" id="selected-count" value="0">
							<div id="selectedSList" style="height: 300px; overflow: auto; border: 0.5px solid gray; border-radius: 15px;">
                            </div>
                        </div>
						<div class="col-md-2">
							<input type="hidden" name="search_api_url" id="search_api_url" value="<?= site_url('site/search?key='); ?>">
                            <input style="border-radius: 15px;" type="text" class="form-control" name="site-key" id="site-key" placeholder="SEARCH FOR SITES">
							<div id="fullSList" style="height: 300px; overflow: auto; border: 0.5px solid gray; border-radius: 15px;">
							</div>
						</div>
					</div>
				</div>
			</div>
          	<div class="box-footer">
            	<button type="submit" class="btn btn-success">
            		<i class="fa fa-check"></i> ADD
            	</button>
          	</div>
            <?php echo form_close(); ?>
      	</div>
    </div>
</div>